import "../globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Interview Room - Complete your interview!",
  description: "Generated by create next app",
};

export default function InterviewLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
